### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [Hem3X/discord-ui-mockup#1]
Hello @Hem3X , thanks for your efforts!
The goal is to check and improve skill of creating markup based on design or mockup.
This is looking quite far from original:
 - different fonts, sizes, colors, paddings, margins
 - has no adaptive.

Could you also make a screenshot of messenger which you took as a base

**Comment by Hem3X** [comment]
Hi @IlyaMokin , thanks for responding!
![ss (2020-08-20 at 05 52 15)](https://user-images.githubusercontent.com/64840109/90789654-d2ddfe80-e30f-11ea-8694-654e05b4d3c0.png)
Most of the colors are the same as in this app. I tried to use similar paddings and margins, but there is a lot of classes in the app that I have no idea how to implement. Open sans seems close enough to orignal. Original font seems to be paid-only.
In the meantime I made some updates for my page to look a bit more like original.
Also I could have made two replies on google form. If that is so please pardon me.

**Comment by ilya4321** [comment]
The PR is accepted, thanks!
